services:
  catalogdb:
    image: mongo:8

  productcatalog.api:
    image: ${DOCKER_REGISTRY-}productcatalogapi
    build:
      context: .
      dockerfile: Services/ProductCatalog/ProductCatalog.API/Dockerfile

volumes:
  mongo_data:
