services:
  catalogdb:
    container_name: catalogdb
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  productcatalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017/?replicaSet=rs0"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductSpuCollectionName=ProductSpu"
      - "DatabaseSettings__ProductSkusCollectionName=ProductSkus"
      - "DatabaseSettings__BrandCollectionName=Brands"
      - "DatabaseSettings__TypeCollectionName=Types"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
